Update contribute.rst
kasenvr/vircadia-docs-sphinx pull request #78
Opened 2020-09-12 04:31 UTC by JulianGro

2020-09-14 00:51 UTC, ctrlaltdavid requested changes

2020-09-14 00:51 UTC, ctrlaltdavid commented on docs/source/contribute.rst
> +There is tons of ways you can contribute to the various parts that make the Vircadia project.
```suggestion
There are tons of ways you can contribute to the various parts that make up Vircadia.
```

2020-09-14 00:51 UTC, ctrlaltdavid commented on docs/source/contribute.rst
> +You can help creating and maintaining the documentation in several ways:
```suggestion
You can help create and maintain the documentation in several ways:
```

2020-09-14 00:51 UTC, ctrlaltdavid commented on docs/source/contribute.rst
> +- `Review changes <https://github.com/kasenvr/vircadia-docs-sphinx/pulls?q=is%3Apr+is%3Aopen+label%3A"needs+review">`_ to the documentation on Github. Currently we would like to have two reviews for
```suggestion
- `Review changes <https://github.com/kasenvr/vircadia-docs-sphinx/pulls?q=is%3Apr+is%3Aopen+label%3A"needs+review">`_ to the documentation on Github. We would like to have two reviewers for most changes, as there are always things that the writer and the first reviewer overlook.
```

2020-09-14 00:51 UTC, ctrlaltdavid commented on docs/source/contribute.rst
> +As an international project, Vircadia relies on translators to be able to reach users that do not speak english.
```suggestion
As an international project, Vircadia relies on translators to be able to reach users that do not speak English.
```

2020-09-14 00:51 UTC, ctrlaltdavid commented on docs/source/contribute.rst
> +You can help translating on our online translation system `Weblate <https://weblate.vircadia.dev>`_ by either submitting translations or becoming a maintainer for your language and checking translati
```suggestion
You can help translating using our online translation system `Weblate <https://weblate.vircadia.dev>`_ by either submitting translations or becoming a maintainer for your language and checking translations before they make it into the documentation.
```

2020-09-14 00:51 UTC, ctrlaltdavid commented on docs/source/contribute.rst
> +While we do not have an entity to manage donations, you can donate to specific members of the team via various services like PayPal or Patreon.
```suggestion
While we do not have an entity to manage donations, you can donate to specific members of the team via various services like PayPal, Patreon, or GitHub Sponsors.
```

2020-09-14 00:51 UTC, ctrlaltdavid commented on docs/source/contribute.rst
> +You can also put bounties on specific features you want to see implemented or issues you want to see fixed, by leaving a comment on our `issue tracker <https://github.com/kasenvr/project-athena>`_.
```suggestion
You can also put bounties on specific features you want to see implemented or issues you want to see fixed, by leaving a comment on our `issue tracker <https://github.com/kasenvr/project-athena/issues>`_.
```

2020-09-14 00:51 UTC, ctrlaltdavid commented on docs/source/contribute.rst
> +Of course bounties are also an option for other parts of the project like the documentation.
```suggestion
Of course, bounties are also an option for other parts of the project like the documentation.
```

2020-09-14 00:51 UTC, ctrlaltdavid commented on docs/source/contribute.rst
> +Most of the developers are highly trained and experienced, normally earning upwards of 40$ an hour on the free market. Keep that in mind if you want to see something done that no one is personally in
```suggestion
Most of the developers are highly trained and experienced, normally earning upwards of 40$ an hour on the free market. Keep that in mind if you want to see something done that no one else is personally interested in.
```

2020-09-14 00:51 UTC, ctrlaltdavid commented on docs/source/contribute.rst
> +- filing issues on our `issue tracker <https://github.com/kasenvr/project-athena>`_,
```suggestion
- filing issues on our `issue tracker <https://github.com/kasenvr/project-athena/issues>`_,
```

2020-09-14 00:51 UTC, ctrlaltdavid commented on docs/source/contribute.rst
> +If you are a developer you can contribute directly to the project via pull request. Keep the `guidelines <https://github.com/kasenvr/project-athena/blob/master/CONTRIBUTING.md>`_ in mind when contrib
```suggestion
If you are a developer, you can contribute directly to the project via pull requests. Keep the `guidelines <https://github.com/kasenvr/project-athena/blob/master/CONTRIBUTING.md>`_ in mind when contributing to the main software.
```

2020-09-14 00:51 UTC, ctrlaltdavid commented on docs/source/contribute.rst
> +It is tremendously helpful for a developers to have someone they can ask when they need work outside of their area of experience done.
```suggestion
It is tremendously helpful for a developers to have someone they can ask when they need work done outside of their area of experience.
```

2020-09-14 03:27 UTC, JulianGro commented
@ctrlaltdavid I took all your suggestions. Keep in mind that this was a draft, since I still hadn't decided if I wanted to add more pages and I hadn't proof read it myself yet.

2020-09-14 03:34 UTC, ctrlaltdavid approved these changes

2020-10-05 20:24 UTC, kasenvr requested changes

2020-10-05 20:24 UTC, kasenvr commented on docs/source/contribute.rst
> +You can help the general development of the Vircadia project without being much a of a developer yourself by:
```suggestion
You can help the general development of the Vircadia project without being a developer yourself by:
```

2020-10-05 20:24 UTC, kasenvr commented on docs/source/contribute.rst
> +It is tremendously helpful for a developers to have someone they can ask when they need work done outside of their area of experience.
```suggestion
It is tremendously helpful for developers to have someone that they can ask for assistance when they need work done that is outside their area of expertise.
```

2020-10-05 20:24 UTC, kasenvr commented on docs/source/contribute.rst
> +Miscellaneous work
```suggestion
Miscellaneous Work
```

2020-10-05 20:24 UTC, kasenvr commented on docs/source/contribute.rst
> +The bounties are based on trust, so if you are unsure about something speak to a core developer or bring it up at a community or developer meeting.
```suggestion
Bounties are created and assigned based on trust, so if you are unsure about something regarding one then speak to a core developer or bring it up at a community or developer meeting.
```

2020-10-05 20:24 UTC, kasenvr commented on docs/source/contribute.rst
> +Most of the developers are highly trained and experienced, normally earning upwards of 40$ an hour on the free market. Keep that in mind if you want to see something done that no one else is personal
```suggestion
Most of the developers are highly trained and experienced, normally earning upwards of $40 an hour in the free market. Keep that in mind if you want to see something accomplished that no one else is personally interested in.
```

2020-10-05 20:24 UTC, kasenvr commented on docs/source/contribute.rst
> +Most, if not all, of us work voluntarily without any payment.
```suggestion
Vircadia is primarily driven by the voluntary contributions of its community and core team.
```

2020-10-05 20:24 UTC, kasenvr commented on docs/source/contribute.rst
> +There are tons of ways you can contribute to the various parts that make up Vircadia.
```suggestion
There are plenty of ways you can contribute to the various parts that make up Vircadia.
```

2020-10-05 20:24 UTC, kasenvr commented on docs/source/contribute.rst
> +Our main `GitHub repository <https://github.com/kasenvr/project-athena>`_ contains the source to many of the components of our software for creating virtual worlds.
```suggestion
Our main `git repository <https://github.com/kasenvr/project-athena>`_ contains the source to many of the components of our software for creating virtual worlds.
```

2020-10-05 20:24 UTC, kasenvr commented on docs/source/contribute.rst
> +Our main `GitHub repository <https://github.com/kasenvr/project-athena>`_ contains the source to many of the components of our software for creating virtual worlds.
The reason for this is to keep agnostic what service is hosting the overall git repos as that can change from GitHub at anytime. Whereas things like "Issues" are specific to GitHub potentially and the wording may have to change if it changes from GitHub anyway.

2020-10-05 20:24 UTC, kasenvr commented on docs/source/contribute.rst
> +- Report errors or missing information to the `Github issue tracker <https://github.com/kasenvr/vircadia-docs-sphinx/issues>`_.
```suggestion
- Report errors or missing information to the `GitHub issue tracker <https://github.com/kasenvr/vircadia-docs-sphinx/issues>`_.
```

2020-10-05 20:24 UTC, kasenvr commented on docs/source/contribute.rst
> +- Create or change documentation pages and open a `PR (pull request) on Github <https://github.com/kasenvr/vircadia-docs-sphinx/pulls>`_.
```suggestion
- Create or change documentation pages and open a `PR (pull request) on GitHub <https://github.com/kasenvr/vircadia-docs-sphinx/pulls>`_.
```

2020-10-06 22:18 UTC, kasenvr approved these changes

2020-10-06 22:18 UTC, kasenvr commented on docs/source/contribute.rst
> +Most of the developers are highly trained and experienced, normally earning upwards of $40 an hour in the free market. Keep that in mind if you want to see something accomplished that no one else is
```suggestion
Most of the developers are highly trained and experienced, normally earning upwards of US$40 an hour in the free market. Keep that in mind if you want to see something accomplished that no one else is personally interested in.
```

2020-10-06 22:18 UTC, kasenvr commented on docs/source/contribute.rst
> +Most of the developers are highly trained and experienced, normally earning upwards of $40 an hour in the free market. Keep that in mind if you want to see something accomplished that no one else is
One last thing, heh, I realized that $40 may not make sense to everyone unless specified to be USD. :)

2020-10-06 23:35 UTC, merged