Add Gallery page
kasenvr/vircadia-docs-sphinx pull request #85
Opened 2020-09-29 14:49 UTC by JulianGro

This PR adds a Gallery page for visitors to take a look at Vircadia.

2020-10-06 19:01 UTC, ctrlaltdavid requested changes
Kalila may prefer the dates reading, "September 28th, 2020" etc.
(Personally, I'd go for "28 Sep 2020".)

2020-10-06 23:28 UTC, JulianGro commented on docs/source/explore/gallery.rst
> +Here are some pictures of past events and interface elements.
The idea was to show more, but I don't necessarily want to show the Meeting Room in the Explore app 6 times and most other ui elements are to be changed in the near future.

2020-10-06 23:32 UTC, JulianGro commented
> Kalila may prefer the dates reading, "September 28th, 2020" etc.
> (Personally, I'd go for "28 Sep 2020".)

I don't care too much about the date format. I just needs to make clear which is the day, which is the month and which is the year. We also have plenty of space so I feel like it makes sense to fully write out the month.

2020-10-07 00:16 UTC, ctrlaltdavid approved these changes

2020-10-09 06:22 UTC, kasenvr commented
Heh, I agree on writing the dates out in order... Month first is confusing, I've been making an effort to convert dates to be DD/MM/YY.

2020-10-09 06:47 UTC, kasenvr requested changes

2020-10-09 06:47 UTC, kasenvr commented on docs/source/explore/gallery.rst
> +Here are some pictures of past events and Interface elements.
```suggestion
This gallery showcases the Vircadia Interface and some past events and locations attended with it.
```

2020-10-09 06:47 UTC, kasenvr commented on docs/source/explore/gallery.rst
> +    Maker meeting, 28th September 2020, on the "El Papa Viejo" (meaning "The Big Pope").
```suggestion
    Maker Meeting, 28th September 2020, on the "El Papa Viejo" (meaning "The Old Pope").
```

2020-10-09 06:47 UTC, kasenvr commented on docs/source/explore/gallery.rst
> +    Maker meeting, 28th September 2020, on the "El Papa Viejo" (meaning "The Big Pope").
Viejo means "old" instead of "big" from as far as I can find from internet resources.

2020-10-09 06:47 UTC, kasenvr commented on docs/source/explore/gallery.rst
> +    Vircadia running on Linux Mint, 19.3 29th September 2020.
```suggestion
    Vircadia running on Linux Mint 19.3, 29th September 2020.
```

2020-10-09 06:47 UTC, kasenvr commented on docs/source/explore/gallery.rst
> +    Dale Glass speaking at the Developer meeting, 20th September 2020.
```suggestion
    Dale Glass speaking at the Developer Meeting, 20th September 2020.
```

2020-10-09 06:47 UTC, kasenvr commented on docs/source/explore.rst
> +If its your first time using Vircadia, you'll start your journey a local space by yourself, where you can experiment with the controls and learn about the product. When you are ready, try exploring o
```suggestion
If it's your first time using Vircadia, you'll start your journey in a local tutorial space by yourself, where you can experiment with the controls and learn about the Interface. When you are ready, try exploring other domains using the Explore app and socialize with people around the metaverse. If you've visited Vircadia before, you will return to the location where you last visited.
```

2020-10-09 06:47 UTC, kasenvr commented on docs/source/explore.rst
>  Vircadia is a metaverse where you can connect and create with others. We invite you to explore VR worlds created in Vircadia and interact with other users. You can visit your friend's VR world, meet
```suggestion
Vircadia is a metaverse where you can connect and create with others. We invite you to explore the worlds created in Vircadia and interact with other users. You can visit friends' virtual worlds, meet people, attend events, and learn about creation in virtuality. It's an immersive and interactive experience with realistic visuals and audio.
```

2020-10-09 06:47 UTC, kasenvr commented on docs/source/explore/gallery.rst
> +    :alt: Community meeting 13th July 2020
```suggestion
    :alt: Community Meeting 13th July 2020
```

2020-10-09 06:47 UTC, kasenvr commented on docs/source/explore/gallery.rst
> +    :alt: Developer meeting 20th September 2020
```suggestion
    :alt: Developer Meeting 20th September 2020
```

2020-10-09 09:55 UTC, JulianGro commented
> Heh, I agree on writing the dates out in order... Month first is confusing, I've been making an effort to convert dates to be DD/MM/YY.

Just keep in mind that DD/MM/YY might be even more confusing in places like the docs, since the docs are written in american english and nor british english. I feel like we should always use the full month or its abbreviation instead of a number.

2020-10-09 10:00 UTC, kasenvr commented
> 
> 
> > Heh, I agree on writing the dates out in order... Month first is confusing, I've been making an effort to convert dates to be DD/MM/YY.
> 
> Just keep in mind that DD/MM/YY might be even more confusing in places like the docs, since the docs are written in american english and not british english (or at least most of it is and I try to keep it uniform). I feel like we should always use the full month or its abbreviation instead of a number.

I agree, what I had meant is that I do like the idea of doing day, month, year. I simply used numerical abbreviations to demonstrate that, not suggesting to use it here. :) Writing it out is fine if there is space given it won't look weird.

2020-10-09 16:19 UTC, SilverfishVR commented
ISO8601, because it's an actual standard, confusion free, and cleverly, sorting by date is just numeric sorting

2020-10-10 04:35 UTC, kasenvr approved these changes
Looks good to me. :) We can adjust dates on another pass if needed, such as when updating the photos to be newer.

2020-10-10 09:56 UTC, merged