Add release notes for 2020.3.1 Demeter
kasenvr/vircadia-docs-sphinx pull request #91
Opened 2020-10-23 05:44 UTC by kasenvr

Also updated release note dates to follow ISO 8601 spec.

2020-10-23 20:07 UTC, JulianGro commented on docs/source/release-notes/2020-3-1-Demeter.md
> +* Application: Set GL preference to 'GLVND' from 'LEGACY' then revert back to 'LEGACY'. (#763, #806)
It went from undefined to GLVND and then to LEGACY again. =P

2020-10-23 20:13 UTC, ctrlaltdavid requested changes

2020-10-23 20:13 UTC, ctrlaltdavid commented on docs/source/release-notes/2020-3-1-Demeter.md
> +* Application: Update shortcut names to include the "Vircadia" in them. (#651)
```suggestion
* Application: Update shortcut names to include "Vircadia" in them. (#651)
```

2020-10-23 20:13 UTC, ctrlaltdavid commented on docs/source/release-notes/2020-3-1-Demeter.md
> +* UI: Add a checkbox for more details to messages logged in entity scripts such as the scriptURL and function with line numbers. (#669)
```suggestion
* UI: Add a checkbox for more details to messages logged in entity scripts such as the script URL and function with line numbers. (#669)
```

2020-10-23 20:13 UTC, ctrlaltdavid commented on docs/source/release-notes/2020-3-1-Demeter.md
> +* Fix sandbox closing if the launcher is closed.
```suggestion
* Fix Sandbox closing if the launcher is closed.
```

2020-10-25 18:59 UTC, ctrlaltdavid approved these changes

2020-10-25 22:52 UTC, merged