Some docs updates.
kasenvr/vircadia-docs-sphinx pull request #96
Opened 2020-11-17 07:31 UTC by kasenvr

2020-11-17 20:15 UTC, ctrlaltdavid approved these changes

2020-11-18 15:22 UTC, JulianGro requested changes
There is a good amount of outdated stuff around, which I didn't comment on. This is likely worth a bigger sweep later.

2020-11-18 15:22 UTC, JulianGro commented on docs/source/create.rst
> +Vircadia enables people connected by interest, community, and friendship to come together and express their creativity with each other. We invite you to personalize your own experience by creating av
```suggestion
Vircadia enables people connected by interest, community, and friendship to come together and express their creativity with each other. We invite you to personalize your own experience by creating avatars and content, and developing apps and scripts. To truly make the metaverse your own, creating your own world or building your immersive project using the free and openly licensed Vircadia engine is encouraged!
```
Might be a lot of "and"s, but at least it should be grammatically correct.

2020-11-18 15:22 UTC, JulianGro commented on docs/source/create/environments.rst
> +|                        | `import them into your Vircadia domain                                                              |
```suggestion
|                        | `import them into your Vircadia Domain                                                              |
```

2020-11-18 15:22 UTC, JulianGro commented on docs/source/create/environments.rst
> +| A Content Archive File | Vircadia domain settings have downloadable content archives. These archives are zip                 |
```suggestion
| A Content Archive File | Vircadia Domain settings have downloadable content archives. These archives are zip                 |
```

2020-11-18 15:22 UTC, JulianGro commented on docs/source/faq.rst
> +| * **Mac**: ~/Library/Application Support/Vircadia/domain-server                                     |
```suggestion
| * **Mac**: ~/Library/Application Support/Vircadia/domain-server/                                    |
| * **Linux**: /var/lib/vircadia/default/domain-server/                                               |
```

2020-11-18 15:22 UTC, JulianGro commented on docs/source/faq.rst
> +| * **Windows**: %AppData%/Roaming/Vircadia/domain-server                                             |
```suggestion
| * **Windows**: %AppData%\Roaming\Vircadia\domain-server\                                            |
```

2020-11-30 11:28 UTC, JulianGro approved these changes

2020-12-01 10:08 UTC, merged